# Generated by Django 4.1.7 on 2024-02-24 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('weight_kg', models.FloatField(default=0.0, help_text='Weight in kilograms')),
                ('height_ft', models.FloatField(default=0.0, help_text='Height in feet')),
                ('food_recommendations', models.TextField(blank=True, default='', null=True)),
                ('bio', models.CharField(max_length=100)),
                ('conditions', models.ManyToManyField(choices=[('Food Allergies', 'Food Allergies'), ('Celiac Disease', 'Celiac Disease'), ('Diabetes', 'Diabetes'), ('Diabetes (Hyperglycemia)', 'Diabetes (Hyperglycemia)'), ('Diabetes (Hypoglycemia)', 'Diabetes (Hypoglycemia)'), ('Hypertension', 'Hypertension'), ('Hyperlipidemia', 'Hyperlipidemia'), ('Obesity', 'Obesity'), ('Gastrointestinal Disorders', 'Gastrointestinal Disorders'), ('Heart Disease', 'Heart Disease'), ('Kidney Disease', 'Kidney Disease'), ('Gout', 'Gout'), ('Food Intolerances', 'Food Intolerances'), ('Eating Disorders', 'Eating Disorders'), ('Malnutrition', 'Malnutrition'), ('Gestational Conditions', 'Gestational Conditions'), ('Thyroid Disorders', 'Thyroid Disorders')], to='userprofile.condition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
